/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BatchImportProviders: typeof import('./src/components/provider/BatchImportProviders.vue')['default']
    BatchImportSuppliers: typeof import('./src/components/supplier/BatchImportSuppliers.vue')['default']
    BatchUpdateModelsModal: typeof import('./src/components/provider/BatchUpdateModelsModal.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    ModelDiffViewer: typeof import('./src/components/provider/ModelDiffViewer.vue')['default']
    ModelListEditor: typeof import('./src/components/provider/ModelListEditor.vue')['default']
    ModelRenameManager: typeof import('./src/components/provider/ModelRenameManager.vue')['default']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NH4: typeof import('naive-ui')['NH4']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NTable: typeof import('naive-ui')['NTable']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    PageFooter: typeof import('./src/components/layout/parts/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/layout/parts/PageHeader.vue')['default']
    PageSider: typeof import('./src/components/layout/parts/PageSider.vue')['default']
    ProviderForm: typeof import('./src/components/provider/ProviderForm.vue')['default']
    ProviderTable: typeof import('./src/components/provider/ProviderTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerManager: typeof import('./src/components/system/ServerManager.vue')['default']
    SupplierForm: typeof import('./src/components/supplier/SupplierForm.vue')['default']
    SupplierTable: typeof import('./src/components/supplier/SupplierTable.vue')['default']
  }
}
