/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/logs': RouteRecordInfo<'/logs', '/logs', Record<never, never>, Record<never, never>>,
    '/provider': RouteRecordInfo<'/provider', '/provider', Record<never, never>, Record<never, never>, '/provider/' | '/provider/[id].edit' | '/provider/add' | '/provider/batch-update'>,
    '/provider/': RouteRecordInfo<'/provider/', '/provider', Record<never, never>, Record<never, never>>,
    '/provider/[id].edit': RouteRecordInfo<'/provider/[id].edit', '/provider/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/provider/add': RouteRecordInfo<'/provider/add', '/provider/add', Record<never, never>, Record<never, never>>,
    '/provider/batch-update': RouteRecordInfo<'/provider/batch-update', '/provider/batch-update', Record<never, never>, Record<never, never>>,
    '/server_config': RouteRecordInfo<'/server_config', '/server_config', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/about.vue': {
      routes: '/about'
      views: never
    }
    'src/pages/dashboard.vue': {
      routes: '/dashboard'
      views: never
    }
    'src/pages/logs.vue': {
      routes: '/logs'
      views: never
    }
    'src/pages/provider.vue': {
      routes: '/provider' | '/provider/' | '/provider/[id].edit' | '/provider/add' | '/provider/batch-update'
      views: 'default'
    }
    'src/pages/provider/index.vue': {
      routes: '/provider/'
      views: never
    }
    'src/pages/provider/[id].edit.vue': {
      routes: '/provider/[id].edit'
      views: never
    }
    'src/pages/provider/add.vue': {
      routes: '/provider/add'
      views: never
    }
    'src/pages/provider/batch-update.vue': {
      routes: '/provider/batch-update'
      views: never
    }
    'src/pages/server_config.vue': {
      routes: '/server_config'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
